# Generated by Django 5.2.7 on 2025-10-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analyzer_an_created_736626_idx')],
            },
        ),
    ]
